# Stubs for scipy.signal.windows (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .windows import *

# Names in __all__ with no definition:
#   barthann
#   bartlett
#   blackman
#   blackmanharris
#   bohman
#   boxcar
#   chebwin
#   cosine
#   dpss
#   exponential
#   flattop
#   gaussian
#   general_cosine
#   general_gaussian
#   general_hamming
#   get_window
#   hamming
#   hann
#   hanning
#   kaiser
#   nuttall
#   parzen
#   slepian
#   triang
#   tukey
