# Stubs for scipy.misc (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .common import *
from .pilutil import *
from . import doccer as doccer
from typing import Any, Optional

comb: Any
logsumexp: Any
factorial: Any
factorial2: Any
factorialk: Any
pade: Any
who: Any
source: Any

def info(object: Optional[Any] = ..., maxwidth: int = ..., output: Any = ..., toplevel: str = ...): ...

# Names in __all__ with no definition:
#   ascent
#   bytescale
#   central_diff_weights
#   derivative
#   electrocardiogram
#   face
#   fromimage
#   imfilter
#   imread
#   imresize
#   imrotate
#   imsave
#   imshow
#   toimage
