# Stubs for scipy.sparse.csgraph._validation (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ._tools import csgraph_from_dense, csgraph_from_masked, csgraph_masked_from_dense, csgraph_to_dense
from typing import Any

DTYPE: Any

def validate_graph(csgraph: Any, directed: Any, dtype: Any = ..., csr_output: bool = ..., dense_output: bool = ..., copy_if_dense: bool = ..., copy_if_sparse: bool = ..., null_value_in: int = ..., null_value_out: Any = ..., infinity_null: bool = ..., nan_null: bool = ...): ...
