# Stubs for scipy.conftest (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def pytest_runtest_setup(item: Any) -> None: ...
def check_fpu_mode(request: Any) -> None: ...
