# Stubs for scipy.version (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

short_version: str
version: str
full_version: str
git_revision: str
release: bool
version = full_version
