# Stubs for scipy.optimize._trlib (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ._trlib import TRLIBQuadraticSubproblem as TRLIBQuadraticSubproblem
from typing import Any

def get_trlib_quadratic_subproblem(tol_rel_i: Any = ..., tol_rel_b: Any = ..., disp: bool = ...): ...
