# Stubs for scipy.sparse.linalg.isolve._gcrotmk (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def gcrotmk(A: Any, b: Any, x0: Optional[Any] = ..., tol: float = ..., maxiter: int = ..., M: Optional[Any] = ..., callback: Optional[Any] = ..., m: int = ..., k: Optional[Any] = ..., CU: Optional[Any] = ..., discard_C: bool = ..., truncate: str = ..., atol: Optional[Any] = ...): ...
