# Stubs for scipy.sparse.linalg.isolve._iterative (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

cbicgrevcom: Any
cbicgstabrevcom: Any
ccgrevcom: Any
ccgsrevcom: Any
cgmresrevcom: Any
cqmrrevcom: Any
dbicgrevcom: Any
dbicgstabrevcom: Any
dcgrevcom: Any
dcgsrevcom: Any
dgmresrevcom: Any
dqmrrevcom: Any
sbicgrevcom: Any
sbicgstabrevcom: Any
scgrevcom: Any
scgsrevcom: Any
sgmresrevcom: Any
sqmrrevcom: Any
zbicgrevcom: Any
zbicgstabrevcom: Any
zcgrevcom: Any
zcgsrevcom: Any
zgmresrevcom: Any
zqmrrevcom: Any
