# Stubs for scipy.sparse.linalg.isolve.lgmres (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def lgmres(A: Any, b: Any, x0: Optional[Any] = ..., tol: float = ..., maxiter: int = ..., M: Optional[Any] = ..., callback: Optional[Any] = ..., inner_m: int = ..., outer_k: int = ..., outer_v: Optional[Any] = ..., store_outer_Av: bool = ..., prepend_outer_v: bool = ..., atol: Optional[Any] = ...): ...
