# Stubs for scipy.sparse.linalg.isolve.lsmr (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def lsmr(A: Any, b: Any, damp: float = ..., atol: float = ..., btol: float = ..., conlim: float = ..., maxiter: Optional[Any] = ..., show: bool = ..., x0: Optional[Any] = ...): ...
