# Stubs for scipy.sparse.linalg.isolve.lsqr (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def lsqr(A: Any, b: Any, damp: float = ..., atol: float = ..., btol: float = ..., conlim: float = ..., iter_lim: Optional[Any] = ..., show: bool = ..., calc_var: bool = ..., x0: Optional[Any] = ...): ...
