# Stubs for scipy.sparse.linalg.isolve.minres (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def minres(A: Any, b: Any, x0: Optional[Any] = ..., shift: float = ..., tol: float = ..., maxiter: Optional[Any] = ..., M: Optional[Any] = ..., callback: Optional[Any] = ..., show: bool = ..., check: bool = ...): ...
