# Stubs for scipy.sparse.linalg.isolve.utils (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

__docformat__: str
__all__: Any
_coerce_rules: Any

def coerce(x: Any, y: Any): ...
def id(x: Any): ...
def make_system(A: Any, M: Any, x0: Any, b: Any): ...
