# Stubs for scipy.special._ellip_harm (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ._ellip_harm_2 import _ellipsoid, _ellipsoid_norm
from ._ufuncs import _ellip_harm
from typing import Any

def ellip_harm(h2: Any, k2: Any, n: Any, p: Any, s: Any, signm: int = ..., signn: int = ...): ...

_ellip_harm_2_vec: Any

def ellip_harm_2(h2: Any, k2: Any, n: Any, p: Any, s: Any): ...
def _ellip_normal_vec(h2: Any, k2: Any, n: Any, p: Any): ...

def ellip_normal(h2: Any, k2: Any, n: Any, p: Any): ...
