# Stubs for scipy.special._logsumexp (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def logsumexp(a: Any, axis: Optional[Any] = ..., b: Optional[Any] = ..., keepdims: bool = ..., return_sign: bool = ...): ...
