# Stubs for scipy.special.add_newdocs (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

docdict: Any

def get(name: Any): ...
def add_newdoc(place: Any, name: Any, doc: Any) -> None: ...
