# Stubs for scipy.special.lambertw (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ._ufuncs import _lambertw
from typing import Any

def lambertw(z: Any, k: int = ..., tol: float = ...): ...
