# Stubs for scipy.special.specfun (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

airyzo: Any
aswfb: Any
bernoa: Any
bernob: Any
cerzo: Any
chgm: Any
clpmn: Any
clpn: Any
clqmn: Any
clqn: Any
cpbdn: Any
cva1: Any
cyzo: Any
eulera: Any
eulerb: Any
fcoef: Any
fcszo: Any
herzo: Any
jdzo: Any
jyzo: Any
klvnzo: Any
lagzo: Any
lamn: Any
lamv: Any
legzo: Any
lpmn: Any
lpmns: Any
lpn: Any
lpni: Any
lqmn: Any
lqmns: Any
lqna: Any
lqnb: Any
othpl: Any
pbdv: Any
pbvv: Any
rctj: Any
rcty: Any
segv: Any
