# Stubs for scipy.sparse.linalg.eigen.arpack._arpack (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

cnaupd: Any
cneupd: Any
debug: Any
dnaupd: Any
dneupd: Any
dsaupd: Any
dseupd: Any
snaupd: Any
sneupd: Any
ssaupd: Any
sseupd: Any
timing: Any
znaupd: Any
zneupd: Any
