# Stubs for scipy.interpolate.dfitpack (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

bispeu: Any
bispev: Any
curfit: Any
dblint: Any
fpchec: Any
fpcurf0: Any
fpcurf1: Any
fpcurfm1: Any
parcur: Any
parder: Any
pardeu: Any
percur: Any
regrid_smth: Any
regrid_smth_spher: Any
spalde: Any
spherfit_lsq: Any
spherfit_smth: Any
splder: Any
splev: Any
splint: Any
sproot: Any
surfit_lsq: Any
surfit_smth: Any
