# Stubs for scipy.signal (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .waveforms import *
from .spline import *
from .bsplines import *
from .filter_design import *
from .fir_filter_design import *
from .ltisys import *
from .lti_conversion import *
from .signaltools import *
from .spectral import *
from .wavelets import *
from ._peak_finding import *
from . import sigtools as sigtools, windows as windows
from ._max_len_seq import max_len_seq as max_len_seq
from ._savitzky_golay import savgol_coeffs as savgol_coeffs, savgol_filter as savgol_filter
from ._upfirdn import upfirdn as upfirdn
from .windows import get_window as get_window, hanning as hanning
from __future__ import absolute_import as absolute_import, division as division, print_function as print_function

# Names in __all__ with no definition:
#   BadCoefficients
#   StateSpace
#   TransferFunction
#   ZerosPolesGain
#   abcd_normalize
#   argrelextrema
#   argrelmax
#   argrelmin
#   band_stop_obj
#   barthann
#   bartlett
#   bessel
#   besselap
#   bilinear
#   bilinear_zpk
#   blackman
#   blackmanharris
#   bode
#   bohman
#   boxcar
#   bspline
#   bsplines
#   buttap
#   butter
#   buttord
#   cascade
#   cheb1ap
#   cheb1ord
#   cheb2ap
#   cheb2ord
#   chebwin
#   cheby1
#   cheby2
#   check_COLA
#   chirp
#   choose_conv_method
#   cmplx_sort
#   coherence
#   cont2discrete
#   convolve
#   convolve2d
#   correlate
#   correlate2d
#   cosine
#   csd
#   cspline1d
#   cspline1d_eval
#   cspline2d
#   cubic
#   cwt
#   daub
#   dbode
#   decimate
#   deconvolve
#   detrend
#   dfreqresp
#   dimpulse
#   dlsim
#   dlti
#   dstep
#   ellip
#   ellipap
#   ellipord
#   exponential
#   fftconvolve
#   filter_design
#   filtfilt
#   find_peaks
#   find_peaks_cwt
#   findfreqs
#   fir_filter_design
#   firls
#   firwin
#   firwin2
#   flattop
#   freqresp
#   freqs
#   freqs_zpk
#   freqz
#   freqz_zpk
#   gauss_spline
#   gaussian
#   gausspulse
#   general_gaussian
#   group_delay
#   hamming
#   hann
#   hilbert
#   hilbert2
#   iirdesign
#   iirfilter
#   iirnotch
#   iirpeak
#   impulse
#   impulse2
#   invres
#   invresz
#   istft
#   kaiser
#   kaiser_atten
#   kaiser_beta
#   kaiserord
#   lfilter
#   lfilter_zi
#   lfiltic
#   lombscargle
#   lp2bp
#   lp2bp_zpk
#   lp2bs
#   lp2bs_zpk
#   lp2hp
#   lp2hp_zpk
#   lp2lp
#   lp2lp_zpk
#   lsim
#   lsim2
#   lti
#   lti_conversion
#   ltisys
#   medfilt
#   medfilt2d
#   minimum_phase
#   morlet
#   normalize
#   nuttall
#   order_filter
#   parzen
#   peak_prominences
#   peak_widths
#   periodogram
#   place_poles
#   qmf
#   qspline1d
#   qspline1d_eval
#   qspline2d
#   quadratic
#   remez
#   resample
#   resample_poly
#   residue
#   residuez
#   ricker
#   sawtooth
#   sepfir2d
#   signaltools
#   slepian
#   sos2tf
#   sos2zpk
#   sosfilt
#   sosfilt_zi
#   sosfiltfilt
#   sosfreqz
#   spectral
#   spectrogram
#   spline
#   spline_filter
#   square
#   ss2tf
#   ss2zpk
#   step
#   step2
#   stft
#   sweep_poly
#   symiirorder1
#   symiirorder2
#   tf2sos
#   tf2ss
#   tf2zpk
#   triang
#   tukey
#   unique_roots
#   unit_impulse
#   vectorstrength
#   waveforms
#   wavelets
#   welch
#   wiener
#   zpk2sos
#   zpk2ss
#   zpk2tf
