# Stubs for scipy.signal._max_len_seq (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def max_len_seq(nbits: Any, state: Optional[Any] = ..., length: Optional[Any] = ..., taps: Optional[Any] = ...): ...
