# Stubs for scipy.signal._max_len_seq_inner (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def __pyx_unpickle_Enum(*args, **kwargs) -> Any: ...
def _max_len_seq_inner(*args, **kwargs) -> Any: ...
