# Stubs for scipy.signal._upfirdn_apply (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

_apply: Any

def __pyx_unpickle_Enum(*args, **kwargs) -> Any: ...
def _output_len(*args, **kwargs) -> Any: ...
