# Stubs for scipy.linalg._cython_signature_generator (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

sig_types: Any

def get_type(info: Any, arg: Any): ...
def make_signature(filename: Any): ...
def get_sig_name(line: Any): ...
def sigs_from_dir(directory: Any, outfile: Any, manual_wrappers: Optional[Any] = ..., exclusions: Optional[Any] = ...) -> None: ...

lapack_manual_wrappers: str
