# Stubs for scipy.linalg._decomp_ldl (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def ldl(A: Any, lower: bool = ..., hermitian: bool = ..., overwrite_a: bool = ..., check_finite: bool = ...): ...
