# Stubs for scipy.linalg._decomp_qz (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def qz(A: Any, B: Any, output: str = ..., lwork: Optional[Any] = ..., sort: Optional[Any] = ..., overwrite_a: bool = ..., overwrite_b: bool = ..., check_finite: bool = ...): ...
def ordqz(A: Any, B: Any, sort: str = ..., output: str = ..., overwrite_a: bool = ..., overwrite_b: bool = ..., check_finite: bool = ...): ...
