# Stubs for scipy.linalg._expm_frechet (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def expm_frechet(A: Any, E: Any, method: Optional[Any] = ..., compute_expm: bool = ..., check_finite: bool = ...): ...
def expm_cond(A: Any, check_finite: bool = ...): ...
