# Stubs for scipy.linalg._flinalg (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

cdet_c: Any
cdet_r: Any
clu_c: Any
ddet_c: Any
ddet_r: Any
dlu_c: Any
sdet_c: Any
sdet_r: Any
slu_c: Any
zdet_c: Any
zdet_r: Any
zlu_c: Any
