# Stubs for scipy.linalg._generate_pyx (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

BASE_DIR: Any
fortran_types: Any
c_types: Any

def arg_names_and_types(args: Any): ...

pyx_func_template: str
npy_types: Any

def arg_casts(arg: Any): ...
def pyx_decl_func(name: Any, ret_type: Any, args: Any, header_name: Any): ...

pyx_sub_template: str

def pyx_decl_sub(name: Any, args: Any, header_name: Any): ...

blas_pyx_preamble: str

def make_blas_pyx_preamble(all_sigs: Any): ...

lapack_pyx_preamble: str

def make_lapack_pyx_preamble(all_sigs: Any): ...

blas_py_wrappers: str

def generate_blas_pyx(func_sigs: Any, sub_sigs: Any, all_sigs: Any, header_name: Any): ...

lapack_py_wrappers: str

def generate_lapack_pyx(func_sigs: Any, sub_sigs: Any, all_sigs: Any, header_name: Any): ...

pxd_template: str

def pxd_decl(name: Any, ret_type: Any, args: Any): ...

blas_pxd_preamble: str

def generate_blas_pxd(all_sigs: Any): ...

lapack_pxd_preamble: str

def generate_lapack_pxd(all_sigs: Any): ...

fortran_template: str
dims: Any

def process_fortran_name(name: Any, funcname: Any): ...
def fort_subroutine_wrapper(name: Any, ret_type: Any, args: Any): ...
def generate_fortran(func_sigs: Any): ...
def make_c_args(args: Any): ...

c_func_template: str

def c_func_decl(name: Any, return_type: Any, args: Any): ...

c_sub_template: str

def c_sub_decl(name: Any, return_type: Any, args: Any): ...

c_preamble: str
lapack_decls: str
cpp_guard: str
c_end: str

def generate_c_header(func_sigs: Any, sub_sigs: Any, all_sigs: Any, lib_name: Any): ...
def split_signature(sig: Any): ...
def filter_lines(lines: Any): ...
def all_newer(src_files: Any, dst_files: Any): ...
def make_all(blas_signature_file: str = ..., lapack_signature_file: str = ..., blas_name: str = ..., lapack_name: str = ..., blas_fortran_name: str = ..., lapack_fortran_name: str = ..., blas_header_name: str = ..., lapack_header_name: str = ...): ...
