# Stubs for scipy.linalg._matfuncs_sqrtm (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import numpy as np
from typing import Any

class SqrtmError(np.linalg.LinAlgError): ...

def sqrtm(A: Any, disp: bool = ..., blocksize: int = ...): ...
