# Stubs for scipy.linalg._procrustes (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def orthogonal_procrustes(A: Any, B: Any, check_finite: bool = ...): ...
