# Stubs for scipy.linalg._sketches (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def clarkson_woodruff_transform(input_matrix: Any, sketch_size: Any, seed: Optional[Any] = ...): ...
