# Stubs for scipy.linalg.blas (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from scipy.linalg._fblas import *
from typing import Any, Optional

def find_best_blas_type(arrays: Any = ..., dtype: Optional[Any] = ...): ...
def get_blas_funcs(names: Any, arrays: Any = ..., dtype: Optional[Any] = ...): ...
