# Stubs for scipy.linalg.cython_lapack (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def _test_dlamch(*args, **kwargs) -> Any: ...
def _test_slamch(*args, **kwargs) -> Any: ...
