# Stubs for scipy.linalg.decomp_schur (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def schur(a: Any, output: str = ..., lwork: Optional[Any] = ..., overwrite_a: bool = ..., sort: Optional[Any] = ..., check_finite: bool = ...): ...
def rsf2csf(T: Any, Z: Any, check_finite: bool = ...): ...
