# Stubs for scipy.linalg.flinalg (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def get_flinalg_funcs(names: Any, arrays: Any = ..., debug: int = ...): ...
