# Stubs for scipy.linalg.lapack (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from scipy.linalg._flapack import *
from typing import Any, Optional

def get_lapack_funcs(names: Any, arrays: Any = ..., dtype: Optional[Any] = ...): ...
