# Stubs for scipy.linalg.linalg_version (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

major: int
minor: int
micro: int
linalg_version: Any
