# Stubs for scipy.linalg.misc (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from numpy.linalg import LinAlgError as LinAlgError
from typing import Any, Optional

class LinAlgWarning(RuntimeWarning): ...

def norm(a: Any, ord: Optional[Any] = ..., axis: Optional[Any] = ..., keepdims: bool = ...): ...
