# Stubs for scipy.io.arff (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .arffread import *

# Names in __all__ with no definition:
#   ArffError
#   MetaData
#   ParseArffError
#   loadarff
