# Stubs for scipy.sparse.linalg.eigen (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

#from __future__ import absolute_import as absolute_import, division as division, print_function as print_function
#from .arpack import *
#from .lobpcg import *

# Names in __all__ with no definition:
#   ArpackError
#   ArpackNoConvergence
#   arpack
#   eigs
#   eigsh
#   lobpcg
#   svds
