# Stubs for scipy.sparse (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .base import *
from .csr import *
from .csc import *
from .lil import *
from .dok import *
from .coo import *
from .dia import *
from .bsr import *
from .construct import *
from .extract import *
from ._matrix_io import *
from . import csgraph as csgraph
from __future__ import absolute_import as absolute_import, division as division, print_function as print_function

# Names in __all__ with no definition:
#   SparseEfficiencyWarning
#   SparseWarning
#   base
#   block_diag
#   bmat
#   bsr
#   bsr_matrix
#   compressed
#   construct
#   coo
#   coo_matrix
#   csc
#   csc_matrix
#   csr
#   csr_matrix
#   data
#   dia
#   dia_matrix
#   diags
#   dok
#   dok_matrix
#   extract
#   eye
#   find
#   hstack
#   identity
#   issparse
#   isspmatrix
#   isspmatrix_bsr
#   isspmatrix_coo
#   isspmatrix_csc
#   isspmatrix_csr
#   isspmatrix_dia
#   isspmatrix_dok
#   isspmatrix_lil
#   kron
#   kronsum
#   lil
#   lil_matrix
#   load_npz
#   rand
#   random
#   save_npz
#   spdiags
#   spmatrix
#   sputils
#   tril
#   triu
#   vstack
