# Stubs for scipy.sparse._matrix_io (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def save_npz(file: Any, matrix: Any, compressed: bool = ...) -> None: ...
def load_npz(file: Any): ...
