# Stubs for scipy.sparse.spfuncs (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def estimate_blocksize(A: Any, efficiency: float = ...): ...
def count_blocks(A: Any, blocksize: Any): ...
