# Stubs for scipy.integrate._odepack (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def odeint(*args, **kwargs) -> Any: ...

class error(Exception): ...
