# Stubs for scipy.integrate._test_multivariate (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

_multivariate_indefinite: int
_multivariate_sin: int
_multivariate_typical: int
_sin_0: int
_sin_1: int
_sin_2: int
_sin_3: int
