# Stubs for scipy.integrate._test_odeint_banded (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

banded5x5: Any
banded5x5_bjac: Any
banded5x5_jac: Any
banded5x5_solve: Any
getbands: Any
jac: Any
