# Stubs for scipy.integrate._ivp.ivp (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .base import OdeSolver
from .bdf import BDF
from .common import EPS, OdeSolution
from .lsoda import LSODA
from .radau import Radau
from .rk import RK23, RK45
from scipy.optimize import OptimizeResult
from typing import Any, Optional

METHODS: Any
MESSAGES: Any

class OdeResult(OptimizeResult): ...

def prepare_events(events: Any): ...
def solve_event_equation(event: Any, sol: Any, t_old: Any, t: Any): ...
def handle_events(sol: Any, events: Any, active_events: Any, is_terminal: Any, t_old: Any, t: Any): ...
def find_active_events(g: Any, g_new: Any, direction: Any): ...
def solve_ivp(fun: Any, t_span: Any, y0: Any, method: str = ..., t_eval: Optional[Any] = ..., dense_output: bool = ..., events: Optional[Any] = ..., vectorized: bool = ..., **options: Any): ...
