# Stubs for scipy.special._precompute.expn_asy (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

x: Any

def generate_A(K: Any): ...

WARNING: str

def main() -> None: ...
