# Stubs for scipy.special._precompute.zetac (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def zetac_series(N: Any): ...
def main() -> None: ...
