# Stubs for scipy.spatial (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .kdtree import *
from .ckdtree import *
from .qhull import *
from ._plotutils import *
from . import distance as distance
from ._procrustes import procrustes as procrustes
from ._spherical_voronoi import SphericalVoronoi as SphericalVoronoi
from __future__ import absolute_import as absolute_import, division as division, print_function as print_function

# Names in __all__ with no definition:
#   ConvexHull
#   Delaunay
#   HalfspaceIntersection
#   KDTree
#   Rectangle
#   Voronoi
#   cKDTree
#   ckdtree
#   convex_hull_plot_2d
#   delaunay_plot_2d
#   distance_matrix
#   kdtree
#   minkowski_distance
#   minkowski_distance_p
#   qhull
#   tsearch
#   voronoi_plot_2d
