# Stubs for scipy.spatial._hausdorff (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def __pyx_unpickle_Enum(*args, **kwargs) -> Any: ...
def directed_hausdorff(*args, **kwargs) -> Any: ...
