# Stubs for scipy.spatial._voronoi (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def __pyx_unpickle_Enum(*args, **kwargs) -> Any: ...
def sort_vertices_of_regions(*args, **kwargs) -> Any: ...
