# Stubs for scipy.odr.__odrpack (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def _set_exceptions(odr_error, odr_stop) -> Any: ...
def odr(*args, **kwargs) -> Any: ...
