# Stubs for scipy.odr.models (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from scipy.odr.odrpack import Model as Model
from typing import Any

multilinear: Any

def polynomial(order: Any): ...

exponential: Any
unilinear: Any
quadratic: Any
