# Stubs for scipy.sparse.linalg._norm (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def norm(x: Any, ord: Optional[Any] = ..., axis: Optional[Any] = ...): ...
