# Stubs for scipy.sparse.linalg._onenormest (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def onenormest(A: Any, t: int = ..., itmax: int = ..., compute_v: bool = ..., compute_w: bool = ...): ...
