# Stubs for scipy.stats._constants (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

_EPS: Any
_XMAX: Any
_LOGXMAX: Any
_XMIN: Any
_EULER: float
_ZETA3: float
