# Stubs for scipy.stats._stats_mstats_common (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from collections import namedtuple
from typing import Any, Optional

LinregressResult = namedtuple('LinregressResult', ['slope', 'intercept', 'rvalue', 'pvalue', 'stderr'])

def linregress(x: Any, y: Optional[Any] = ...): ...
def theilslopes(y: Any, x: Optional[Any] = ..., alpha: float = ...): ...
def _find_repeats(arr: Any): ...
