# Stubs for scipy.stats._tukeylambda_stats (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

_tukeylambda_var_pc: Any
_tukeylambda_var_qc: Any
_tukeylambda_var_p: Any
_tukeylambda_var_q: Any

def tukeylambda_variance(lam: Any): ...

_tukeylambda_kurt_pc: Any
_tukeylambda_kurt_qc: Any
_tukeylambda_kurt_p: Any
_tukeylambda_kurt_q: Any

def tukeylambda_kurtosis(lam: Any): ...
