# Stubs for scipy.cluster._optimal_leaf_ordering (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

is_valid_dm: Any
is_valid_y: Any
squareform: Any

def __pyx_unpickle_Enum(*args, **kwargs) -> Any: ...
def optimal_leaf_ordering(*args, **kwargs) -> Any: ...
