# Stubs for scipy.cluster._vq (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def update_cluster_means(*args, **kwargs) -> Any: ...
def vq(*args, **kwargs) -> Any: ...
