# Stubs for scipy.optimize (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .optimize import *
from ._minimize import *
from ._root import *
from .minpack import *
from .zeros import *
from .nonlin import *
from ._basinhopping import basinhopping as basinhopping
from ._constraints import Bounds as Bounds, LinearConstraint as LinearConstraint, NonlinearConstraint as NonlinearConstraint
from ._differentialevolution import differential_evolution as differential_evolution
from ._hessian_update_strategy import BFGS as BFGS, HessianUpdateStrategy as HessianUpdateStrategy, SR1 as SR1
from ._hungarian import linear_sum_assignment as linear_sum_assignment
from ._linprog import linprog as linprog, linprog_verbose_callback as linprog_verbose_callback
from ._lsq import least_squares as least_squares, lsq_linear as lsq_linear
from .cobyla import fmin_cobyla as fmin_cobyla
from .lbfgsb import LbfgsInvHessProduct as LbfgsInvHessProduct, fmin_l_bfgs_b as fmin_l_bfgs_b
from .nnls import nnls as nnls
from .slsqp import fmin_slsqp as fmin_slsqp
from .tnc import fmin_tnc as fmin_tnc
from __future__ import absolute_import as absolute_import, division as division, print_function as print_function

# Names in __all__ with no definition:
#   OptimizeResult
#   OptimizeWarning
#   anderson
#   approx_fprime
#   bisect
#   bracket
#   brent
#   brenth
#   brentq
#   broyden1
#   broyden2
#   brute
#   check_grad
#   cobyla
#   curve_fit
#   diagbroyden
#   excitingmixing
#   fixed_point
#   fmin
#   fmin_bfgs
#   fmin_cg
#   fmin_ncg
#   fmin_powell
#   fminbound
#   fsolve
#   golden
#   lbfgsb
#   leastsq
#   line_search
#   linearmixing
#   linesearch
#   minimize
#   minimize_scalar
#   minpack
#   minpack2
#   moduleTNC
#   newton
#   newton_krylov
#   nonlin
#   optimize
#   ridder
#   root
#   rosen
#   rosen_der
#   rosen_hess
#   rosen_hess_prod
#   show_options
#   slsqp
#   tnc
#   zeros
