# Stubs for scipy.optimize._minimize (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def minimize(fun: Any, x0: Any, args: Any = ..., method: Optional[Any] = ..., jac: Optional[Any] = ..., hess: Optional[Any] = ..., hessp: Optional[Any] = ..., bounds: Optional[Any] = ..., constraints: Any = ..., tol: Optional[Any] = ..., callback: Optional[Any] = ..., options: Optional[Any] = ...): ...
def minimize_scalar(fun: Any, bracket: Optional[Any] = ..., bounds: Optional[Any] = ..., args: Any = ..., method: str = ..., tol: Optional[Any] = ..., options: Optional[Any] = ...): ...
