# Stubs for scipy.optimize._root (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def root(fun: Any, x0: Any, args: Any = ..., method: str = ..., jac: Optional[Any] = ..., tol: Optional[Any] = ..., callback: Optional[Any] = ..., options: Optional[Any] = ...): ...
