# Stubs for scipy.optimize._trustregion_ncg (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ._trustregion import BaseQuadraticSubproblem, _minimize_trust_region
from typing import Any, Optional

__all__: Any

def _minimize_trust_ncg(fun: Any, x0: Any, args: Any = ..., jac: Optional[Any] = ..., hess: Optional[Any] = ..., hessp: Optional[Any] = ..., **trust_region_options: Any): ...

class CGSteihaugSubproblem(BaseQuadraticSubproblem):
    def solve(self, trust_radius: Any): ...
