# Stubs for scipy.optimize._trustregion_krylov (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def _minimize_trust_krylov(fun: Any, x0: Any, args: Any = ..., jac: Optional[Any] = ..., hess: Optional[Any] = ..., hessp: Optional[Any] = ..., inexact: bool = ..., **trust_region_options: Any): ...
