# Stubs for scipy.optimize.cobyla (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

izip = zip

def fmin_cobyla(func: Any, x0: Any, cons: Any, args: Any = ..., consargs: Optional[Any] = ..., rhobeg: float = ..., rhoend: float = ..., maxfun: int = ..., disp: Optional[Any] = ..., catol: float = ...): ...
