# Stubs for scipy.optimize.nnls (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def nnls(A: Any, b: Any, maxiter: Optional[Any] = ...): ...
