# Stubs for scipy.optimize.slsqp (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def approx_jacobian(x: Any, func: Any, epsilon: Any, *args: Any): ...
def fmin_slsqp(func: Any, x0: Any, eqcons: Any = ..., f_eqcons: Optional[Any] = ..., ieqcons: Any = ..., f_ieqcons: Optional[Any] = ..., bounds: Any = ..., fprime: Optional[Any] = ..., fprime_eqcons: Optional[Any] = ..., fprime_ieqcons: Optional[Any] = ..., args: Any = ..., iter: int = ..., acc: float = ..., iprint: int = ..., disp: Optional[Any] = ..., full_output: int = ..., epsilon: Any = ..., callback: Optional[Any] = ...): ...
