# Stubs for scipy.optimize.tnc (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def fmin_tnc(func: Any, x0: Any, fprime: Optional[Any] = ..., args: Any = ..., approx_grad: int = ..., bounds: Optional[Any] = ..., epsilon: float = ..., scale: Optional[Any] = ..., offset: Optional[Any] = ..., messages: Any = ..., maxCGit: int = ..., maxfun: Optional[Any] = ..., eta: int = ..., stepmx: int = ..., accuracy: int = ..., fmin: int = ..., ftol: int = ..., xtol: int = ..., pgtol: int = ..., rescale: int = ..., disp: Optional[Any] = ..., callback: Optional[Any] = ...): ...
