# Stubs for scipy._build_utils (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ._fortran import *
from typing import Any

numpy_nodepr_api: Any
test: Any
