# Stubs for scipy.io.matlab (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from . import byteordercodes as byteordercodes
from .mio import loadmat as loadmat, savemat as savemat, whosmat as whosmat
