# Stubs for scipy.io.matlab.byteordercodes (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

sys_is_le: Any
native_code: Any
swapped_code: Any
aliases: Any

def to_numpy_code(code: Any): ...
