# Stubs for scipy.io.matlab.mio5_params (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import numpy as np
from .miobase import convert_dtypes
from typing import Any, Optional

miINT8: int
miUINT8: int
miINT16: int
miUINT16: int
miINT32: int
miUINT32: int
miSINGLE: int
miDOUBLE: int
miINT64: int
miUINT64: int
miMATRIX: int
miCOMPRESSED: int
miUTF8: int
miUTF16: int
miUTF32: int
mxCELL_CLASS: int
mxSTRUCT_CLASS: int
mxOBJECT_CLASS: int
mxCHAR_CLASS: int
mxSPARSE_CLASS: int
mxDOUBLE_CLASS: int
mxSINGLE_CLASS: int
mxINT8_CLASS: int
mxUINT8_CLASS: int
mxINT16_CLASS: int
mxUINT16_CLASS: int
mxINT32_CLASS: int
mxUINT32_CLASS: int
mxINT64_CLASS: int
mxUINT64_CLASS: int
mxFUNCTION_CLASS: int
mxOPAQUE_CLASS: int
mxOBJECT_CLASS_FROM_MATRIX_H: int
mdtypes_template: Any
mclass_dtypes_template: Any
mclass_info: Any
NP_TO_MTYPES: Any
NP_TO_MXTYPES: Any
codecs_template: Any

def _convert_codecs(template: Any, byte_order: Any): ...

MDTYPES: Any
_def: Any

class mat_struct: ...

class MatlabObject(np.ndarray):
    def __new__(cls, input_array: Any, classname: Optional[Any] = ...): ...
    classname: Any = ...
    def __array_finalize__(self, obj: Any) -> None: ...

class MatlabFunction(np.ndarray):
    def __new__(cls, input_array: Any): ...

class MatlabOpaque(np.ndarray):
    def __new__(cls, input_array: Any): ...

OPAQUE_DTYPE: Any
