# Stubs for scipy.io.matlab.mio_utils (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def chars_to_strings(*args, **kwargs) -> Any: ...
def squeeze_element(*args, **kwargs) -> Any: ...
