# Stubs for scipy.ndimage._ni_label (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

get_nonzero_line: Any
get_read_line: Any
get_write_line: Any

def __pyx_unpickle_Enum(*args, **kwargs) -> Any: ...
def _label(*args, **kwargs) -> Any: ...

class NeedMoreBits(Exception): ...
