# Stubs for scipy.ndimage.io (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def imread(fname: Any, flatten: bool = ..., mode: Optional[Any] = ...): ...
