# Stubs for scipy.fftpack._fftpack (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

cfft: Any
cfftnd: Any
crfft: Any
dct1: Any
dct2: Any
dct3: Any
ddct1: Any
ddct2: Any
ddct3: Any
ddst1: Any
ddst2: Any
ddst3: Any
destroy_cfft_cache: Any
destroy_cfftnd_cache: Any
destroy_dct1_cache: Any
destroy_dct2_cache: Any
destroy_ddct1_cache: Any
destroy_ddct2_cache: Any
destroy_ddst1_cache: Any
destroy_ddst2_cache: Any
destroy_drfft_cache: Any
destroy_dst1_cache: Any
destroy_dst2_cache: Any
destroy_rfft_cache: Any
destroy_zfft_cache: Any
destroy_zfftnd_cache: Any
drfft: Any
dst1: Any
dst2: Any
dst3: Any
rfft: Any
zfft: Any
zfftnd: Any
zrfft: Any
