# Stubs for scipy.fftpack.convolve (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

convolve: Any
convolve_z: Any
destroy_convolve_cache: Any
init_convolution_kernel: Any
