# Stubs for scipy.fftpack.helper (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from numpy.fft.helper import fftfreq as fftfreq, fftshift as fftshift, ifftshift as ifftshift
from typing import Any

def rfftfreq(n: Any, d: float = ...): ...
def next_fast_len(target: Any): ...
