# Stubs for scipy.io (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ._fortran import FortranFile as FortranFile
from .harwell_boeing import hb_read as hb_read, hb_write as hb_write
from .idl import readsav as readsav
from .matlab import byteordercodes as byteordercodes, loadmat as loadmat, savemat as savemat, whosmat as whosmat
from .mmio import mminfo as mminfo, mmread as mmread, mmwrite as mmwrite
from .netcdf import netcdf_file as netcdf_file, netcdf_variable as netcdf_variable
from __future__ import absolute_import as absolute_import, division as division, print_function as print_function

# Names in __all__ with no definition:
#   harwell_boeing
#   idl
#   matlab
#   mmio
#   netcdf
