# Stubs for scipy.io._test_fortran (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

read_unformatted_double: Any
read_unformatted_int: Any
read_unformatted_mixed: Any
