# Stubs for scipy.io.wavfile (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

class WavFileWarning(UserWarning): ...

def read(filename: Any, mmap: bool = ...): ...
def write(filename: Any, rate: Any, data: Any) -> None: ...
