# Stubs for scipy.optimize._lsq (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .least_squares import least_squares as least_squares
from .lsq_linear import lsq_linear as lsq_linear
