# Stubs for scipy.optimize._lsq.bvls (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .common import print_header_linear, print_iteration_linear
from typing import Any

def compute_kkt_optimality(g: Any, on_bound: Any): ...
def bvls(A: Any, b: Any, x_lsq: Any, lb: Any, ub: Any, tol: Any, max_iter: Any, verbose: Any): ...
