# Stubs for scipy.optimize._lsq.givens_elimination (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def __pyx_unpickle_Enum(*args, **kwargs) -> Any: ...
def givens_elimination(*args, **kwargs) -> Any: ...
