# Stubs for scipy.optimize._lsq.lsq_linear (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .bvls import bvls
from .common import compute_grad, in_bounds
from .trf_linear import trf_linear
from typing import Any, Optional

def prepare_bounds(bounds: Any, n: Any): ...

TERMINATION_MESSAGES: Any

def lsq_linear(A: Any, b: Any, bounds: Any = ..., method: str = ..., tol: float = ..., lsq_solver: Optional[Any] = ..., lsmr_tol: Optional[Any] = ..., max_iter: Optional[Any] = ..., verbose: int = ...): ...
