# Stubs for scipy.optimize._trustregion_constr (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .minimize_trustregion_constr import _minimize_trustregion_constr as _minimize_trustregion_constr
