# Stubs for scipy.optimize._trustregion_constr.equality_constrained_sqp (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def equality_constrained_sqp(fun_and_constr: Any, grad_and_jac: Any, lagr_hess: Any, x0: Any, fun0: Any, grad0: Any, constr0: Any, jac0: Any, stop_criteria: Any, state: Any, initial_penalty: Any, initial_trust_radius: Any, factorization_method: Any, trust_lb: Optional[Any] = ..., trust_ub: Optional[Any] = ..., scaling: Any = ...): ...
