# Stubs for scipy.optimize._trustregion_constr.projections (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def orthogonality(A: Any, g: Any): ...
def projections(A: Any, method: Optional[Any] = ..., orth_tol: float = ..., max_refin: int = ..., tol: float = ...): ...
